services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      HOST: "${HOST}"
      PORT: "${PORT}"
    develop:
      watch:
        - action: sync
          path: .
          target: ./
