services:
  back:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      HOST: "${HOST}"
      PORT: "${PORT}"
    develop:
      watch:
        - action: sync
          path: ./
          target: ./
  front:
    build:
      context: ./frontend/my_first_app
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./frontend/my_first_app
          target: ./frontend/my_first_app
